Update the README file
redhat-beyond/Hotails pull request #15
Opened 2022-03-08 15:27 UTC by jeniaSakirko

This PR is for updating the readme file with basic information about the project
You can see that the contributing file from #2 is mentioned so the PR should be merged after the file

closes #14

2022-03-08 16:16 UTC, Omeramsc requested changes
Added a few comments

BTW, you could've removed the `contributing.md` mention and have the contributing PR add it, therefore removing the dependencies between them, :)

2022-03-08 16:16 UTC, Omeramsc commented on README.md
> +What things you need to install the software and how to install them:
maybe `in order to install the software you should.....`

2022-03-08 16:16 UTC, Omeramsc commented on README.md
> +7. When finished, run `vagrant destroy -f` to tear down the environment
Maybe add a note about all changes getting deleted after doing so.

2022-03-08 17:35 UTC, jeniaSakirko commented
> Added a few comments
> 
> BTW, you could've removed the `contributing.md` mention and have the contributing PR add it, therefore removing the dependencies between them, :)

What do you think about commenting out the contributing part and uncomment in new PR?

2022-03-08 17:37 UTC, jeniaSakirko commented on README.md
> +7. When finished, run `vagrant destroy -f` to tear down the environment
Added

2022-03-08 21:49 UTC, OfirMatasas approved these changes

2022-03-08 22:04 UTC, ErezCohenn reviewed
optional suggestion:
1) adding architecture section that will look something like that:
# Architecture

| Frontend      | Backennd      | Datebase      |
| ------------- | ------------- | ------------- |
| HTML          | Python        | SQLite        |
| CSS           | Django        |  
|  Bootstarp      | Vagrant       |

2) adding team members section that will include our names and photos (optional)

2022-03-09 07:37 UTC, Omeramsc commented
> > Added a few comments
> > BTW, you could've removed the `contributing.md` mention and have the contributing PR add it, therefore removing the dependencies between them, :)
> 
> @Omeramsc What do you think about commenting out the contributing part and uncomment in new PR?

Think about how a new user or developer will interpret it. Comments can be misleading (especially when on a markdown file, and not in code), it is better to either remove it altogether (and so, remove the dependencies), or leave it as is.

2022-03-09 11:38 UTC, jeniaSakirko commented
> optional suggestion:
> 
> 1. adding architecture section that will look something like that:
> 
> # Architecture
> Frontend	Backennd	Datebase
> HTML	Python	SQLite
> CSS	Django	
> Bootstarp	Vagrant	
> 2. adding team members section that will include our names and photos (optional)

1. I think adding the architecture will be relevant in the future now we will only have one column
2. Added the team members

2022-03-09 11:47 UTC, ErezCohenn approved these changes
LGTM

2022-03-09 13:06 UTC, Yuval-Vino approved these changes
After your changes, this README file looks real good! 
Great job!!!

2022-03-09 15:27 UTC, Omeramsc approved these changes
LGTM

2022-03-09 15:27 UTC, merged